In [2]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
plt.style.use('/Users/summer/desktop/notebook.mplstyle');
%config InlineBackend.figure_format = 'retina'
colors = ["#2078B5", "#FF7F0F", "#2CA12C", "#D72827", "#9467BE", "#8C574B",
            "#E478C2", "#808080", "#BCBE20", "#17BED0", "#AEC8E9", "#FFBC79", 
            "#98E08B", "#FF9896", "#C6B1D6", "#C59D94", "#F8B7D3", "#C8C8C8", 
           "#DCDC8E", "#9EDAE6"]

In [17]:
def RK4test(mm):

    k1 = dt*mm
    k2 = dt*(mm + k1*0.5)
    k3 = dt*(mm + k2*0.5*dt)
    k4 = dt*(mm+ k3*dt)

    return mm + (k1 + 2*k2 + 2*k3 + k4)/6

In [19]:
type(ma)

numpy.ndarray

In [38]:
dt = 0.1
ma=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ma)
print(RK4test(ma))

ma[1][1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.10200921 2.20401842 3.30602763]
 [4.40803683 5.51004604 6.61205525]
 [7.71406446 8.81607367 9.91808287]]


5

In [14]:
def lorenz96(xy,i,j):

    xy_dot[i] = (xy[0:I][(i-1)%I] * (xy[0:I][(i+1)%I] - xy[0:I][(i-2)%I]) - xy[0:I][i%I] + F - h*c/b*(np.sum([xy[I::][i::I]])))    
    xy_dot[I+j*I+i] = (c*b*xy[I:][((j+1)%J)*I+i]*(xy[I:][((j-1)%J)*I+i]-xy[I:][((j+2)%J)*I+i])-c*xy[I:][((j)%J)*I+i]+h*c/b*xy[0:I][i])

    #dx[i] = (x[(i-1)%I] * (x[(i+1)%I] - x[(i-2)%I]) - x[i%I] + F - h*c/b*(np.sum([y[jj%J,i] for jj in range(J)])))*dt     
    #dy[j,i] = (c*b*y[(j+1)%J,i]*(y[(j-1)%J,i]-y[(j+2)%J,i])-c*y[(j)%J,i]+h*c/b*x[i])*dt
    #print(i,j,xy_dot)

    return xy_dot

In [15]:
def RK4(xylist,step,i,j):
    
    oldxy = xylist[((I+J*I)*(step-1)):((I+J*I)*(step))]

    k1 = dt*lorenz96(oldxy,i,j)
    k2 = dt*lorenz96(oldxy + k1*0.5*dt,i,j)
    k3 = dt*lorenz96(oldxy + k2*0.5*dt,i,j)
    k4 = dt*lorenz96(oldxy + k3*dt,i,j)

    return oldxy + (k1 + 2*k2 + 2*k3 + k4)/6

In [ ]:
#def J4LE(xy,i,j):   
      
#    xyjj[:I*I][(0+i+I*i)%(I*I)] = (xy[0:I][(i-1)%I] * (xy[0:I][(i+1)%I] - xy[0:I][(i-2)%I]) - 1 + F - h*c/b*(np.sum([xy[I::][i::I]])))  #对角 
#    xyjj[:I*I][(i+I*i)%(I*I)] = (xy[0:I][(i+1)%I] - xy[0:I][(i-2)%I]) - xy[0:I][i%I] + F - h*c/b*(np.sum([xy[I::][i::I]])) #对角下一个
#    xyjj[:I*I][(i+I*i)%(I*I)] = (xy[0:I][(i-1)%I] * xy[0:I][(i+1)%I] -  xy[0:I][(i-2)%I]) - xy[0:I][i%I] + F - h*c/b*(np.sum([xy[I::][i::I]])) # 对角上两个   
#    xyjj[:I*I][(i+I*i)%(I*I)] = (xy[0:I][(i-1)%I] - xy[0:I][(i-1)%I] * xy[0:I][(i-2)%I]) - xy[0:I][i%I] + F - h*c/b*(np.sum([xy[I::][i::I]])) # 对角上一个
    
#    xyjj[I*I+j*I+i] = (c*b*xy[I:][((j+1)%J)*I+i]*(xy[I:][((j-1)%J)*I+i]-xy[I:][((j+2)%J)*I+i])-c*xy[I:][((j)%J)*I+i]+h*c/b  #j 里的 y

In [ ]:
def RK4JJ(xyjj,step,i,j):
    
    #oldxy = xylist[((I+J*I)*(step-1)):((I+J*I)*(step))]
    #should change into for JACOBIAN
    
    xyjj = xylist[((I*I+J*I)*(step-1)):((I*I+J*I)*(step))]
    
    k1 = dt*J4LE(xyjj,i,j)
    k2 = dt*J4LE(xyjj + k1*0.5*dt,i,j)
    k3 = dt*J4LE(xyjj + k2*0.5*dt,i,j)
    k4 = dt*J4LE(xyjj + k3*dt,i,j)

    return xyjj + (k1 + 2*k2 + 2*k3 + k4)/6

In [ ]:
F = 14
c = 10
b = 10
h = 1
dt = 0.0001
totstep = 200000
Jmax = 51
Imax = 51

In [ ]:
l=[8,9,10]
for a in range(len(l)):
    ma[a:] = l[a]

In [51]:
ma=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(ma)
for i in range(4):
    print(ma[i%4][i%4])
print()
for i in range(4):
    print(ma[i%4][(i+1)%4])    
print()
for i in range(4):
    print(ma[(i)%4][(i-1)%4]) 
print()
for i in range(4):
    print(ma[(i)%4][(i-2)%4]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1
6
11
16

2
7
12
13

4
5
10
15

3
8
9
14


In [ ]:
x = np.load('xlisttxt.npy')
y = np.load('ylisttxt.npy')

In [ ]:
#referece
LEcalc(f,Df,x(:,end))  # call
function [LE] = LEcalc(f,Df, v0) #def

f = @(x,par) [par(1)*(x(2)-x(1));
              par(2)*x(1)-x(2)-x(1)*x(3);
              x(1)*x(2)-par(3)*x(3)];

Df = @(x,par) [-par(1),par(1),0;
        par(2)-x(3),-1,-x(1);
        x(2),x(1),-par(3)];

LE = np.zeros((Jmax-4,Imax-4))
print(len(LE[0]))

In [ ]:
def J4LE(xnow,x4jj,y4jj,i,j):   
      
    x4jj[(i)%I][(i)%I]  = (xnow[(i-1)%I] * (xnow[(i+1)%I] - xnow[(i-2)%I]) - 1 + F - h*c/b*(np.sum([y4jj[i::I]])))  #对角 
    x4jj[(i)%I][(i-1)%I]  = (xnow[(i+1)%I] - xnow[(i-2)%I]) - xnow[i%I] + F - h*c/b*(np.sum([y4jj[i::I]])) #对角下一个
    x4jj[(i)%I][(i-2)%I]  = (xnow[(i-1)%I] * xnow[(i+1)%I] -  xnow[(i-2)%I]) - xnow[i%I] + F - h*c/b*(np.sum([y4jj[i::I]])) # 对角下两个   
    x4jj[(i)%I][(i+1)%I]  = (xnow[(i-1)%I] - xnow[(i-1)%I] * xnow[(i-2)%I]) - xnow[i%I] + F - h*c/b*(np.sum([y4jj[i::I]])) # 对角上一个
    
    y4jj[j*I+i] = (c*b*y4jj[((j+1)%J)*I+i]*(y4jj[((j-1)%J)*I+i]-y4jj[((j+2)%J)*I+i])-c*y4jj[((j)%J)*I+i]+h*c/b  #j 里的 y

In [ ]:
m = len(x1)
N = 10000
LE = np.zeros(m)
v = x1

LE = np.zeros((Jmax-4,Imax-4))

for I in np.arange(4,Imax,1):
    for J in np.arange(8,Jmax,1):
        
        xjj = np.zeros((I-4,I-4))
        yjj = []
        
        xylist = np.zeros([(totstep)*(I+J*I)])
        s=0
        newx=[]
        newlist = []
        time=[0]

        for ii in range(I):
            xylist[ii] = x[ii]
        newx.append([x[ii] for ii in range(len(x))])

        for jjj in range(J):
            for iii in range(I):
                xylist[I + jjj*I + iii] = y[jjj,iii]

        for step in np.arange(1,totstep,1):
            xy_dot= np.zeros((I+J*I))
            for i in range(I):
                s+=1
                time.append(s)
                for j in range(J):
                    xylist[(I+J*I)*(step):(I+J*I)*(step+1)] = RK4(xylist,step, i,j) 
                    newlist = xylist[(I+J*I)*(step):(I+J*I)*(step+1)][0:I]
                    
                    
                     for a in range(I):
                        #xjj[a:] = xylist[(I+J*I)*(step):(I+J*I)*(step+1)][0:I][a]
                        xjj[a:] = xylist[(I+J*I)*(step-1):(I+J*I)*(step)][0:I][a]
                        yjj.append(xylist[(I+J*I)*(step-1):(I+J*I)*(step)][I:])
                        
          
               
                    
                    #for a in range(I):
                    #    xyjj.append(xylist[(I+J*I)*(step):(I+J*I)*(step+1)][0:I][a])
                        #xyjj[a:] = xylist[(I+J*I)*(step-1):(I+J*I)*(step)][0:I][a]
                    #    xyjj.append(xylist[(I+J*I)*(step):(I+J*I)*(step+1)][I:])
                    
                newx.append([newlist[ij] for ij in range(len(newlist))])
                
                #for a in range(I):
                #    xyjj[a:] = RK4(xylist,step, i,j)[a]
                    
                
                xyjj[a:] = RK4(xylist,step, i,j)[a]  
                    
                    
                
                
        
LEcalc(f,Df,x(:,end))  # call
function [LE] = LEcalc(f,Df, v0) #def
            
            
print(LE)          
plt.imshow(LE, cmap=plt.cm.jet)
cb = plt.colorbar(label='LE', pad=0.1)
plt.axes().set_aspect('equal')
plt.show()

In [ ]:
def LEcalc(x1):

    q = np.identity(m)

    #JJ=J4LE(xy,i,j) unfinish
    #Jt = A*x;   ode for DF1, 'A' will be current Df

    for i in range(N):

        DF1 = q = np.identity(m)
        
        for step in np.arange(1,totstep,1):
            

            #DF1 = RK4JJ(Jt,DF1,Df,i,j)
            #maybe should add time phase for x1 during x1 to parellal moving with JACOBIAN
            
    
        Z = DF1*q
        [q,r] = np.linalg.qr(Z)
        #LE[]= LE[] + np.log(np.amax(np.absolute(np.diag(r))))/(N)
        #LE = LE + log(abs(diag(r)))/N;
