In [10]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline

In [11]:
def fast_fourier_transform(t,y):
    '''Return the fast Fourier transform of y.'''
    ŷ = np.fft.fft(y)
    ω = 2*np.pi*np.fft.fftfreq(len(time),time[1]-time[0])
    return ω,ŷ

In [12]:
I = 4
J = 8
F = 14

c = 10
b = 10
h = 1

dt = 0.0001
totstep = 2000000

In [13]:
def lorenz96(xy,i,j):

    xy_dot[i] = (xy[0:I][(i-1)%I] * (xy[0:I][(i+1)%I] - xy[0:I][(i-2)%I]) - xy[0:I][i%I] + F - h*c/b*(np.sum([xy[I::][i::I]])))    
    xy_dot[I+j*I+i] = (c*b*xy[I:][((j+1)%J)*I+i]*(xy[I:][((j-1)%J)*I+i]-xy[I:][((j+2)%J)*I+i])-c*xy[I:][((j)%J)*I+i]+h*c/b*xy[0:I][i])

    #dx[i] = (x[(i-1)%I] * (x[(i+1)%I] - x[(i-2)%I]) - x[i%I] + F - h*c/b*(np.sum([y[jj%J,i] for jj in range(J)])))*dt     
    #dy[j,i] = (c*b*y[(j+1)%J,i]*(y[(j-1)%J,i]-y[(j+2)%J,i])-c*y[(j)%J,i]+h*c/b*x[i])*dt
    #print(i,j,xy_dot)

    return xy_dot

In [14]:
def RK4(xylist,step,i,j):
    
    oldxy = xylist[((I+J*I)*(step-1)):((I+J*I)*(step))]

    k1 = dt*lorenz96(oldxy,i,j)
    k2 = dt*lorenz96(oldxy + k1*0.5*dt,i,j)
    k3 = dt*lorenz96(oldxy + k2*0.5*dt,i,j)
    k4 = dt*lorenz96(oldxy + k3*dt,i,j)

    return oldxy + (k1 + 2*k2 + 2*k3 + k4)/6

In [15]:
x = np.random.rand(I)
y = np.random.rand(J,I)
xylist = np.zeros([(totstep)*(I+J*I)])
s=0

print(x)
print()
print(y)
print()

newx=[]
newlist = []
time=[0]

for ii in range(I):
    xylist[ii] = x[ii]
    #newx.append(x[ii])

newx.append([x[ii] for ii in range(len(x))])
print()
print(newx)
print()

for jjj in range(J):
    for iii in range(I):
        xylist[I + jjj*I + iii] = y[jjj,iii]
#print(xylist)

[0.64477081 0.27046374 0.84110887 0.32038798]

[[0.71115951 0.08215477 0.2920163  0.88695206]
 [0.66142933 0.01236276 0.39994903 0.26723111]
 [0.03586989 0.25331264 0.22931919 0.324941  ]
 [0.29802536 0.45370707 0.38964397 0.44056843]
 [0.76884472 0.56972018 0.02850918 0.39059297]
 [0.65720926 0.38113596 0.61768841 0.1188701 ]
 [0.95772669 0.47368205 0.45686188 0.78951962]
 [0.20745803 0.30555431 0.35406211 0.81002354]]


[[0.6447708063064906, 0.2704637383074421, 0.8411088655589655, 0.32038798167896243]]



In [16]:
print(xylist)

[0.64477081 0.27046374 0.84110887 ... 0.         0.         0.        ]


In [ ]:
for step in np.arange(1,totstep,1):
    
    xy_dot= np.zeros((I+J*I))
    
    for i in range(I):
        
        s+=1
        time.append(s*dt)
        
        for j in range(J):
            
            xylist[(I+J*I)*(step):(I+J*I)*(step+1)] = RK4(xylist,step, i,j)
            
            newlist = xylist[(I+J*I)*(step):(I+J*I)*(step+1)][0:I]

        newx.append([newlist[ij] for ij in range(len(newlist))])
    
#print(xylist[-20::])
#print(time)
#print(len(time))

In [ ]:
x1 = np.array([newx[a][0] for a in range(len(newx))])
x2 = np.array([newx[a][1] for a in range(len(newx))])
x3 = np.array([newx[a][2] for a in range(len(newx))])
x4 = np.array([newx[a][3] for a in range(len(newx))])

In [ ]:
print(len(x1))

In [ ]:
np.linspace(0, 10, N, endpoint=True)

In [ ]:
print(x2)

In [ ]:
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.plot(-x2[3000000:], x1[3000000:], x3[3000000:],lw=0.5)
ax.set_xlabel("$x_2$")
ax.set_ylabel("$x_1$")
ax.set_zlabel("$x_4$")
ax.set_title("Lorenz 1996")
plt.show()

In [ ]:
print(len(time))
print(len(x1))

In [ ]:
fig = plt.figure(figsize=(8,5))
plt.scatter(time,x1, s=0.5, marker='.', c='b')
# title and labels
plt.ylabel(r'$x_1$')
plt.xlabel(r'$time$')
plt.title('1996 Lorenz model\n',fontsize=15)
plt.xlim(time[-500000],time[-1])
ax.set_xticklabels([])
#plt.ylim(0,1)
plt.show()

In [ ]:
# Get the discrete FT
ω,ŷ = fast_fourier_transform(time,x1)
print(len(time))
# Plot the real and imaginary parts of the DFT
fig = plt.figure(figsize=(8,5))
plt.loglog(ω,ŷ.real,label='real.',lw=1)
plt.loglog(ω,ŷ.imag,label='imag.',lw=1)
#plt.xlim(0,np.max(ω))
#plt.xlim(1,10**5)
#plt.ylim(-100000,100000)
plt.xlabel('Frequency [rad/s]')
plt.ylabel('Transform [arb.]')
plt.legend(loc='lower right')